### ISSUE TITLE
年终总结Github仓库名称征集和投票

### ISSUE THREAD

**Issue by liaohuqiu** [winter-fall/winter-fall#1]
你近来好么，有过着你想要的生活吗？不知不觉间，我们已经站到了 2015 的尾巴上。

过去一年欢笑和泪水，是否还记得？让我们一起写点什么吧，关于过去，关于未来。

在开始之前，我们需要一起给这个事情，起一个好听的名字，目前我们想到这么几个：
- Goodbye2015Hello2016
- GoodNight2015Morning2016
- Finish2015Start2016
- Bye2015Hi2016

你喜欢哪个？ 这个是我们的投票链接(无需翻墙)： 

https://gdgdocs.org/forms/d/1b3n5_Axo2rid8ZPinbTjToHR5yQ5NZJ5ueSKNuFO3Gk/viewform

如果你有更好的想法，请在这里留言吧！

**Comment by okernel** [comment]
OnStopOnStart

**Comment by inferjay** [comment]
OnStopOnStart不错，仓库名可以不带年份，然后用年份做文件夹或者用带年份的名字做文件夹，要不明年还得想名字

**Comment by liaohuqiu** [comment]
@inferjay 所有文章，全部都是 issue 形式，不是 PR 的形式，应该只有一个 README 文件。所有没有文件夹。

**Comment by inferjay** [comment]
我把这茬给忘了😂

**Comment by linkaipeng** [comment]
From2015To2016
寓意：来自2015的我们给2016写的信，记录2015，展望2016.

**Comment by xiongwei-git** [comment]
已投票 Bye2015Hi2016

**Comment by zhehuaz** [comment]
2015 `:+1:`
`:+1:`直接发出来是:+1:
同时表示2016
给2015点赞，同时迎接2016

**Comment by wangpeiyuan** [comment]
Welcome to 2016

**Comment by andyiac** [comment]
2015 Time to say goodbye

with the music from Sarah Brightman

[Time to say goodbye](http://7xo3oi.com5.z0.glb.qiniucdn.com/Time%20To%20Say%20Goodbye.mp3)

<audio src="http://7xo3oi.com5.z0.glb.qiniucdn.com/Time%20To%20Say%20Goodbye.mp3" controls="controls">

**Comment by ryanhoo** [comment]
@liaohuqiu: A word just pops up in my mind, it’s `forward`. 

It came from a drama which is `The Flash`, said by Professor Stein: 

> Gather around everyone please. Looking at all of you, thinking how far we've all come and remembering those no longer with us, I'm reminded of a Hebrew word used during times of graduation. "Kadima". It means forward. 

Here I take this as a message to you guys as well. Despite everything that has changed and everyone may have experienced wins or losses in the year of 2015, we have to keep moving on. I propose to use this keyword `forward`. 2016, let’s move forward. 

So let's name it: `Bye2015Forward2016`. ;-D

Here is the source: http://www.imdb.com/character/ch0039650/quotes

**Comment by inferjay** [comment]
@ryanhoo 赞，已加入投票表单

**Comment by androidmalin** [comment]
已投递
From2015To2016

**Comment by shinyjacklee** [comment]
我提的是`Bye2015Hi2016`，灵感来自`simple principle`
ryhoo同学的`Forward` 挺好
LangleyChang同学的`2015＋1`很有创意。

**Comment by inferjay** [comment]
@jackL-e-e 好的，我把寓意加上

**Comment by inferjay** [comment]
@ryanhoo 能简单概括下你的寓意吗？

**Comment by ryanhoo** [comment]
@inferjay 我这段话已经表述了呀~ 这是本宝宝说的，不是 Professor Stein 说的。。

> Here I take this as a message to you guys as well. Despite everything that has changed and everyone may have experienced wins or losses in the year of 2015, we have to keep moving on. I propose to use this keyword forward. 2016, let’s move forward.

我想寓意简而言之应该是：**我们回顾 2015，是为了更好的前行。进击吧 2016！**

**Comment by inferjay** [comment]
@ryanhoo 英语太渣，把曲解了你的寓意

**Comment by ryanhoo** [comment]
@inferjay 哈哈哈哈哈哈哈~

**Comment by ryanhoo** [comment]
@inferjay 你把我的寓意写到别人那里去了噜！

**Comment by inferjay** [comment]
@ryanhoo 手误😂

**Comment by SherlockOy** [comment]
投了OnStopOnStart，带感

**Comment by demox2026** [comment]
不错

**Comment by liaohuqiu** [comment]
#3 我们可以开始了。
